### ISSUE TITLE
fetal error 

### ISSUE THREAD

**Issue by mr-X3** [pdftables/php-pdftables-api#1]
i tried to used it but its show 

Fatal error: Call to undefined function curl_file_create() in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\sample\pdftables.php on line 3

error how to solve it ?

**Comment by pwaller** [comment]
Here are a couple of possible answers to your question:

* [Fatal error: Call to undefined function curl_init() using Batch File](https://stackoverflow.com/a/14724799/465384)

* [Call to undefined function curl_file_create() [file handling]](https://stackoverflow.com/a/18363431/465384)

PHP needs to be configured to have the curl plugin available for those functions beginning with `curl_` to work. I've [added this to our README](https://github.com/pdftables/php-pdftables-api/commit/86d6224b696f3f15cc00967a117245aeaa7cf670).

Hope this helps, let us know if you have any other problems!
